import type { Dispatch, RefObject, SetStateAction } from "react";
import type { AppearanceSettings, ThemeMode } from "./features/appearance/types";

/** Permission that can be granted to an MCP client. */
export type Permission = "read" | "search" | "write" | "terminal";

/** Tab displayed inside the onboarding access step. */
export type AccessTab = "folder" | "permissions";

/** Top-level page available in the dashboard. */
export type DashboardTab = "overview" | "access" | "activity" | "settings" | "appearance";

/** Supported public tunnel implementation. */
export type TunnelProvider = "ngrok" | "cloudflared" | "zrok";

/** Operation supported by the profile-name dialog. */
export type ProfileDialogKind = "create" | "duplicate" | "rename";

/** Persisted tunnel configuration used by the Rust backend. */
export type TunnelSettings = {
  provider: TunnelProvider;
  executable: string;
  extra_args: string;
};

/** Complete persisted server profile returned by the Rust backend. */
export type Profile = {
  id: string;
  display_name: string;
  roots: string[];
  port: number;
  host: string;
  max_concurrency: number;
  max_io_concurrency: number;
  read_only: boolean;
  follow_links: boolean;
  max_read_mb: number;
  max_write_mb: number;
  tree_max_depth: number;
  tree_max_entries: number;
  tree_max_warnings: number;
  patch_max_kb: number;
  patch_preview_kb: number;
  max_search_results: number;
  search_max_concurrency: number;
  search_worker_threads: number;
  regex_cache_capacity: number;
  include_hidden: boolean;
  respect_gitignore: boolean;
  terminal_enabled: boolean;
  terminal_max_concurrency: number;
  terminal_default_timeout_ms: number;
  terminal_max_timeout_ms: number;
  terminal_max_output_mb: number;
  terminal_max_read_kb: number;
  terminal_max_wait_ms: number;
  terminal_session_retention_ms: number;
  oauth_enabled: boolean;
  oauth_require_auth: boolean;
  oauth_issuer: string | null;
  log_tools: boolean;
  tunnel: TunnelSettings | null;
};

/** Persisted profile collection and currently active profile identifier. */
export type ProfileState = {
  schema_version: number;
  active_profile_id: string;
  profiles: Profile[];
};

/** Exportable client configuration generated by the backend. */
export type ClientSnippet = { id: string; title: string; content: string };

/** Current server and tunnel process status. */
export type RuntimeStatus = {
  running: boolean;
  tunnel_running: boolean;
  tunnel_provider: TunnelProvider | null;
  public_url: string | null;
  tunnel_error: string | null;
};

/** Form-friendly representation of advanced profile values. */
export type AdvancedConfig = {
  host: string;
  followLinks: boolean;
  maxWriteMb: string;
  treeMaxDepth: string;
  treeMaxEntries: string;
  treeMaxWarnings: string;
  patchMaxKb: string;
  patchPreviewKb: string;
  serverConcurrency: string;
  ioConcurrency: string;
  searchConcurrency: string;
  searchWorkers: string;
  regexCacheCapacity: string;
  respectGitignore: boolean;
  terminalConcurrency: string;
  terminalDefaultTimeoutMs: string;
  terminalMaxTimeoutMs: string;
  terminalMaxOutputMb: string;
  terminalMaxReadKb: string;
  terminalMaxWaitMs: string;
  terminalRetentionMs: string;
  oauthEnabled: boolean;
  oauthRequireAuth: boolean;
  oauthIssuer: string;
};

/** Render-ready activity item shown in the dashboard. */
export type ActivityLog = {
  id: string;
  time: string;
  tool: string;
  target: string;
  duration: string;
  status: "ok" | "error";
  client: string;
  error: string | null;
};

/** Raw activity payload emitted by Tauri. */
export type ToolActivityEvent = {
  id: string;
  timestampMs: number;
  tool: string;
  target: string;
  durationUs: number;
  status: "ok" | "error";
  client: string;
  error: string | null;
};

/** Shared editable profile state consumed by onboarding and dashboard pages. */
export type ProfileEditor = {
  profileName: string;
  setProfileName: (value: string) => void;
  roots: string[];
  setRoots: Dispatch<SetStateAction<string[]>>;
  port: string;
  setPort: (value: string) => void;
  selected: Set<Permission>;
  togglePermission: (permission: Permission) => void;
  toolLogs: boolean;
  setToolLogs: (value: boolean) => void;
  maxReadMb: string;
  setMaxReadMb: (value: string) => void;
  searchResults: string;
  setSearchResults: (value: string) => void;
  includeHidden: boolean;
  setIncludeHidden: (value: boolean) => void;
  advanced: AdvancedConfig;
  setAdvanced: Dispatch<SetStateAction<AdvancedConfig>>;
  profileState: ProfileState | null;
  setProfileState: Dispatch<SetStateAction<ProfileState | null>>;
  profileError: string;
  loadingProfiles: boolean;
  applyProfile: (profile: Profile) => void;
  currentProfile: () => Profile;
  saveProfile: () => Promise<boolean>;
  dirty: boolean;
};

/** Theme controls shared by both application shells. */
export type ThemeController = {
  theme: "light" | "dark";
  settings: AppearanceSettings;
  themeVariables: Record<string, string>;
  themeButtonRef: RefObject<HTMLButtonElement | null>;
  toggleTheme: () => void;
  setThemeMode: (mode: ThemeMode) => void;
  updateAppearance: (patch: Partial<AppearanceSettings>) => void;
  resetAppearance: () => void;
};
